In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.2


In [3]:
np? #more detail info about numpy

In [4]:
#numpy array from list
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5), dtype=float) # array dimension as tupple (3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3,5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [8]:
np.arange(0,20,2) # start, end, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5) # five equally spaced value between 0 to 1 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((3,3))

array([[0.83657656, 0.77781175, 0.23082513],
       [0.46676831, 0.11173914, 0.47696074],
       [0.89765447, 0.53908638, 0.08503915]])

In [12]:
np.random.normal((3,3))

array([2.04526263, 4.40721117])

In [13]:
np.random.randint(0,10,(3,3))

array([[3, 6, 2],
       [4, 7, 8],
       [5, 9, 5]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

In [24]:
x = np.random.randint(10,size=6)
print("x shape: ",x.shape)
print("x size: ",x.size)
print("x ndim: ", x.ndim)
print("dtype: ", x.dtype)

x shape:  (6,)
x size:  6
x ndim:  1
dtype:  int64


### Accessing element

In [32]:
x = np.array([np.random.randint(9) for i in range(7)])
print(x)

[0 7 4 7 8 2 8]


In [33]:
x[0]

0

In [34]:
x[1]

7

In [35]:
x[-1]

8

In [36]:
x[-2]

2

In [38]:
x2 = np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
x2[0,2]

3

In [42]:
x2[0,0]=10
x2

array([[10,  2,  3],
       [ 4,  5,  6]])

## Array Slicing: Accessing Subarrays [start:stop:step]

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [45]:
x[5:]

array([5, 6, 7, 8, 9])

In [46]:
x[4:7]

array([4, 5, 6])

In [47]:
x[::2]

array([0, 2, 4, 6, 8])

In [48]:
x[1::2]

array([1, 3, 5, 7, 9])

In [49]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x[5::-2]

array([5, 3, 1])

In [51]:
x2

array([[10,  2,  3],
       [ 4,  5,  6]])

In [52]:
x2[:2, :2]

array([[10,  2],
       [ 4,  5]])

In [53]:
x2[:2,::2]

array([[10,  3],
       [ 4,  6]])

In [54]:
x2[::-1,::-1]

array([[ 6,  5,  4],
       [ 3,  2, 10]])

### Accessing array rows and columns

In [56]:
x2[:,0] #all row, first col

array([10,  4])

In [57]:
x2[0,:] # first row, all cols

array([10,  2,  3])

### Copying array

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x_copy1 = x
x_copy1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x_copy1[0] = 99
print("x_copy1: ",x_copy1)
print("x:",x)

x_copy1:  [99  1  2  3  4  5  6  7  8  9]
x: [99  1  2  3  4  5  6  7  8  9]


We can clearly see, modifying coppied array x_copy1 also modifes the original array x.

In [70]:
print("x befor copy:",x)
x_copy2 = x.copy() # or x_copy2 = x[:]
#x_copy2 = x[:]
x_copy2[0] = 500
print("x_copy2: ",x_copy2)
print("x:",x)

x befor copy: [500   1   2   3   4   5   6   7   8   9]
x_copy2:  [500   1   2   3   4   5   6   7   8   9]
x: [500   1   2   3   4   5   6   7   8   9]


Now, there is no change in the original array x, modifying copied array only modifies to copied array.

## Reshaping of arrays

In [72]:
x = np.arange(1,10).reshape((3,3)) # tupple as dimension
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Concatenation of arrays

In [74]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y]) # arg= tupple or list of array/list

array([1, 2, 3, 3, 2, 1])

In [77]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [78]:
x = np.array([[1,2,3],[4,5,6]])

In [79]:
# concatenate along the first axis
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
# concatenate along the second axis 
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For mixed dimensiona, np.vstack and np.hstack is used.

In [81]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
y = np.array([7,8,9])

In [83]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
z = np.array([[99],[99]])
np.hstack([x,z])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting of arrays

np.split,  np.hsplit, and np.vsplit